apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlops-storage-pvc
  namespace: mlops
  labels:
    app.kubernetes.io/part-of: mlops
    component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard