#!/usr/bin/env python3
"""Generate all 8 CNN/DN/CapsNet example packages for the MLOps monorepo."""

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent  # /Users/avi/Documents/ai
BASE = ROOT / "apps/neural-networks/convolutional-neural-networks"

# ============================================================
# Configuration for all 8 examples
# ============================================================
EXAMPLES = [
    {
        "dir": "cnn/medical-imaging",
        "pkg": "medical_imaging",
        "name": "medical-imaging",
        "title": "Medical Imaging Diagnosis",
        "desc": "Detects tumors or fractures in synthetic medical X-ray, MRI, and CT scan images",
        "class_name": "MedicalImagingCNN",
        "task": "classification",
        "n_classes": 3,
        "label_names": ["normal", "benign", "malignant"],
        "metrics_port": "8016",
        "metrics_prefix": "MEDICAL_IMAGING",
        "loss_type": "categorical cross-entropy",
        "output_activation": "softmax",
        "output_loss": "cross_entropy",
        "response_field": "condition",
        "response_values": "0=normal, 1=benign, 2=malignant",
    },
    {
        "dir": "cnn/facial-recognition",
        "pkg": "facial_recognition",
        "name": "facial-recognition",
        "title": "Facial Recognition",
        "desc": "Binary facial recognition for phone unlock and photo tagging",
        "class_name": "FacialRecognitionCNN",
        "task": "binary_classification",
        "n_classes": 1,
        "label_names": ["not_owner", "owner"],
        "metrics_port": "8017",
        "metrics_prefix": "FACIAL_RECOGNITION",
        "loss_type": "binary cross-entropy",
        "output_activation": "sigmoid",
        "output_loss": "binary_crossentropy",
        "response_field": "is_owner",
        "response_values": "true=owner, false=not_owner",
    },
    {
        "dir": "cnn/video-surveillance",
        "pkg": "video_surveillance",
        "name": "video-surveillance",
        "title": "Video Surveillance",
        "desc": "Tracks crowd movement and spots security threats in real-time frame images",
        "class_name": "VideoSurveillanceCNN",
        "task": "classification",
        "n_classes": 3,
        "label_names": ["normal", "activity", "threat"],
        "metrics_port": "8018",
        "metrics_prefix": "VIDEO_SURVEILLANCE",
        "loss_type": "categorical cross-entropy",
        "output_activation": "softmax",
        "output_loss": "cross_entropy",
        "response_field": "activity",
        "response_values": "0=normal, 1=activity, 2=threat",
    },
    {
        "dir": "dn/image-super-resolution",
        "pkg": "image_super_resolution",
        "name": "image-super-resolution",
        "title": "Image Super-Resolution",
        "desc": "Upscales low-resolution photos and blurry security footage into sharp images",
        "class_name": "ImageSuperResolutionDN",
        "task": "super_resolution",
        "n_classes": 0,
        "label_names": [],
        "metrics_port": "8020",
        "metrics_prefix": "IMAGE_SUPER_RESOLUTION",
        "loss_type": "mean squared error",
        "output_activation": "linear",
        "output_loss": "mse",
        "response_field": "high_res_pixels",
        "response_values": "64 reconstructed pixel values",
    },
    {
        "dir": "dn/semantic-segmentation",
        "pkg": "semantic_segmentation",
        "name": "semantic-segmentation",
        "title": "Semantic Segmentation",
        "desc": "Maps object boundaries in synthetic images for autonomous driving and satellite mapping",
        "class_name": "SemanticSegmentationDN",
        "task": "segmentation",
        "n_classes": 1,
        "label_names": ["background", "foreground"],
        "metrics_port": "8021",
        "metrics_prefix": "SEMANTIC_SEGMENTATION",
        "loss_type": "binary cross-entropy",
        "output_activation": "sigmoid",
        "output_loss": "binary_crossentropy",
        "response_field": "mask",
        "response_values": "64 binary pixel values (0=background, 1=foreground)",
    },
    {
        "dir": "dn/generative-art",
        "pkg": "generative_art",
        "name": "generative-art",
        "title": "Generative Art",
        "desc": "Reconstructs fine details from rough sketches using deconvolutional upsampling",
        "class_name": "GenerativeArtDN",
        "task": "super_resolution",
        "n_classes": 0,
        "label_names": [],
        "metrics_port": "8025",
        "metrics_prefix": "GENERATIVE_ART",
        "loss_type": "mean squared error",
        "output_activation": "linear",
        "output_loss": "mse",
        "response_field": "reconstructed_pixels",
        "response_values": "64 reconstructed pixel values",
    },
    {
        "dir": "capsnet/autonomous-driving",
        "pkg": "autonomous_driving",
        "name": "autonomous-driving",
        "title": "Autonomous Driving Object Recognition",
        "desc": "Recognizes traffic signs and pedestrians accurately even when partially hidden",
        "class_name": "AutonomousDrivingCapsNet",
        "task": "classification",
        "n_classes": 5,
        "label_names": ["stop", "yield", "speed_limit", "pedestrian", "other"],
        "metrics_port": "8022",
        "metrics_prefix": "AUTONOMOUS_DRIVING",
        "loss_type": "categorical cross-entropy",
        "output_activation": "softmax",
        "output_loss": "cross_entropy",
        "response_field": "object_type",
        "response_values": "0=stop, 1=yield, 2=speed_limit, 3=pedestrian, 4=other",
    },
    {
        "dir": "capsnet/medical-scan-analysis",
        "pkg": "medical_scan_analysis",
        "name": "medical-scan-analysis",
        "title": "Medical Scan Analysis",
        "desc": "Identifies overlapping body structures in complex 3D medical scans",
        "class_name": "MedicalScanAnalysisCapsNet",
        "task": "classification",
        "n_classes": 4,
        "label_names": ["bone", "organ", "vessel", "tissue"],
        "metrics_port": "8023",
        "metrics_prefix": "MEDICAL_SCAN_ANALYSIS",
        "loss_type": "categorical cross-entropy",
        "output_activation": "softmax",
        "output_loss": "cross_entropy",
        "response_field": "structure",
        "response_values": "0=bone, 1=organ, 2=vessel, 3=tissue",
    },
    {
        "dir": "capsnet/text-char-recognition",
        "pkg": "text_char_recognition",
        "name": "text-char-recognition",
        "title": "Text and Character Recognition",
        "desc": "Reads distorted captchas and complex handwritten text keeping part-to-whole relationships",
        "class_name": "TextCharRecognitionCapsNet",
        "task": "classification",
        "n_classes": 36,
        "label_names": [str(i) for i in range(10)] + [chr(c) for c in range(ord("A"), ord("Z") + 1)],
        "metrics_port": "8024",
        "metrics_prefix": "TEXT_CHAR_RECOGNITION",
        "loss_type": "categorical cross-entropy",
        "output_activation": "softmax",
        "output_loss": "cross_entropy",
        "response_field": "character",
        "response_values": "0-9, A-Z",
    },
]

IMG_SIZE = 8
N_CHANNELS = 1
N_FEATURES = IMG_SIZE * IMG_SIZE
PKG_NAME = {name}
SCHEMA_NAME = {pkg}
OUTPUT_DIM = {n_classes}
